### ISSUE TITLE
Lawnchair crashing after reboot

### ISSUE THREAD

**Issue by DARKBOYJYOTI** [Unofficial-Life/Lawnchair-Launcher-Module#11]
https://paste.crdroid.net/li6rgx

time: 1728813097407
msg: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
stacktrace: java.lang.RuntimeException: Unable to create service com.android.quickstep.TouchInteractionService: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4511)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7942)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:572)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:557)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:217)
	at com.android.launcher3.LauncherPrefs.getEncryptedPrefs(Unknown Source:7)
	at com.android.launcher3.LauncherPrefs.chooseSharedPreferences(Unknown Source:28)
	at com.android.launcher3.LauncherPrefs.getInner(Unknown Source:0)
	at com.android.launcher3.LauncherPrefs.get(SourceFile:3)
	at com.android.launcher3.util.DisplayController$Info.<init>(SourceFile:31)
	at com.android.launcher3.util.DisplayController.<init>(Unknown Source:98)
	at com.android.launcher3.touch.f.get(Unknown Source:876)
	at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(Unknown Source:6)
	at com.android.launcher3.util.MainThreadInitializedObject.c(Unknown Source:0)
	at com.android.launcher3.dragndrop.a.get(Unknown Source:26)
	at com.android.launcher3.util.TraceHelper.allowIpcs(SourceFile:9)
	at com.android.launcher3.util.MainThreadInitializedObject.get(Unknown Source:33)
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(SourceFile:13)
	at com.android.quickstep.TouchInteractionService.onCreate(Unknown Source:25)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4498)
	... 9 more

**Comment by Unofficial-Life** [comment]
All I can see is your device restricted lawnchair from starting because the device was locked after the restart
